name: manage-azure-policy-d3e85246
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Inherit_a_tag_from_the_subscription_b27a0cbd-a167-4dfa-ae64-4337be671140/**'
#      - .github/workflows/manage-azure-policy-d3e85246.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d3e85246}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Inherit_a_tag_from_the_subscription_b27a0cbd-a167-4dfa-ae64-4337be671140/**
